# Use a Node.js base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) to leverage Docker's caching
COPY package*.json ./

# Install dependencies
RUN npm install 

# Expose the port Next.js development server runs on
EXPOSE 3000

CMD ["npm", "run", "dev"]
